# Generated by Django 4.0.8 on 2022-11-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Molecular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('formula', models.CharField(blank=True, default='', max_length=100)),
                ('effect', models.CharField(blank=True, default='', max_length=500)),
                ('others', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
